image: node

before_script:
  - npm install

stages:
  - build

build_skip_tests:
  stage: build
  script:
    - npm link
    - cd kram
    - yo springboot-kickstart
  only:
    - master
  artifacts:
    paths:
      - kram/
